version: 2.1

workflows:
  gather_configs_cron:
    jobs:
      - gather-configs
    triggers:
      - schedule:
          # gather them daily in the morning
          cron: "35 13 * * *"
          filters:
            branches:
              only:
                - main
  gather_configs:
    jobs:
      - gather-configs


jobs:
  gather-configs:
    docker:
      # Be sure to change this to major.minor version of python you need to support.
      - image: cimg/python:3.9
    # Checkout the code as the first step.
    # The python orb's install-packages step will install the dependencies from a Pipfile via Pipenv by default.
    # Here we're making sure we just pip by default
    # Then run your tests!
    # CircleCI will report the results back to your VCS provider.
    steps:
      - checkout
      - python run.py
      - store_artifacts:
          path: sample
