version: 2.1

workflows:
  gather_configs_cron:
    jobs:
      - gather-configs
    triggers:
      - schedule:
          # gather them daily in the morning
          cron: "35 13 * * *"
          filters:
            branches:
              only:
                - main
  gather_configs_main:
    jobs:
      - gather-configs


jobs:
  gather-configs:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: python run.py
      - store_artifacts:
          path: sample/
